#MODELING SECTION

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Preprocessed_text.csv to Preprocessed_text.csv


In [5]:
df = pd.read_csv("Preprocessed_text.csv")
df.head()

id             category                                               text  \
0   1        storage_issue  pharmacies in giza reported issues with antide...   
1   2        storage_issue  a weekly report from delta region connected an...   
2   3         import_delay  In Giza, anticoagulants availability has dropp...   
3   4  manufacturing_issue  In coastal governorates, anticoagulants availa...   
4   5  manufacturing_issue  Pharmacies in Giza reported issues with asthma...   

   keyword_count  sentiment  risk_score  \
0              0     0.0000           1   
1              1    -0.2732           6   
2              2     0.0000          10   
3              1     0.0000           5   
4              0     0.0000           1   

                                          clean_text  
0  pharmacies giza reported issues antidepressant...  
1  weekly report delta region connected antidepre...  
2  giza anticoagulants availability dropped repor...  
3  coastal governorates anticoagulants availabili...  
4  pharmacies giza reported issues asthma inhaler...

In [6]:
X = df["clean_text"]
y = df["category"]
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (400,)
y shape: (400,)


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (320,)
X_test shape: (80,)
y_train shape: (320,)
y_test shape: (80,)


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000,ngram_range=(1, 2))

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF test shape:", X_test_tfidf.shape)

TF-IDF train shape: (320, 1725)
TF-IDF test shape: (80, 1725)


In [9]:
text_model = LogisticRegression(max_iter=1000, random_state=42)

In [10]:
text_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [11]:
y_pred_text = text_model.predict(X_test_tfidf)

In [12]:
text_accuracy = accuracy_score(y_test, y_pred_text)
text_precision = precision_score(y_test, y_pred_text, average='weighted')
text_cm = confusion_matrix(y_test, y_pred_text)

print("Text Model Accuracy (%):", text_accuracy * 100)
print("Text Model Precision (%):", text_precision * 100)
print("\nConfusion Matrix:")
print(text_cm)

Text Model Accuracy (%): 62.5
Text Model Precision (%): 62.911255411255404

Confusion Matrix:
[[ 0  0  0  0  0  0  0  0  0  1  0  0  1  1  0  0]
 [ 0  5  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  2  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0  0  1  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  2  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  2  1  0  0  1  1  0  0]
 [ 0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  3  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0]
 [ 0  0  1  0  0  0  0  0  1  1  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  0  0  1  1  0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
